# Cloud Build configuration for Test Environment (develop branch)
steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/novara:test-${SHORT_SHA}'
      - '-t'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/novara:test-latest'
      - '.'
    id: 'build-image'

  # Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/novara:test-${SHORT_SHA}'
    id: 'push-image-versioned'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/novara:test-latest'
    id: 'push-image-latest'

  # Deploy to Cloud Run (Test)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'novara-test'
      - '--image'
      - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/novara:test-${SHORT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--cpu'
      - '1'
      - '--memory'
      - '512Mi'
      - '--timeout'
      - '300'
      - '--concurrency'
      - '80'
      - '--port'
      - '3000'
      - '--set-env-vars'
      - 'NODE_ENV=production'
      - '--set-secrets'
      - 'NEXT_PUBLIC_N8N_WEBHOOK_URL=NEXT_PUBLIC_N8N_WEBHOOK_URL:latest,N8N_CALLBACK_SECRET=N8N_CALLBACK_SECRET:latest,NEXT_PUBLIC_SUPABASE_URL=NEXT_PUBLIC_SUPABASE_URL:latest,SUPABASE_SERVICE_ROLE_KEY=SUPABASE_SERVICE_ROLE_KEY:latest,COMET_API_KEY=COMET_API_KEY:latest'
    id: 'deploy-cloud-run'

# Substitution variables
substitutions:
  _REGION: 'us-central1'
  _ARTIFACT_REGISTRY: 'novara-images'

# Options
options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

# Timeout
timeout: '1200s'

# Images to be pushed to registry
images:
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/novara:test-${SHORT_SHA}'
  - '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/novara:test-latest'

