fragment HomeParts on Home {
  __typename
  hero {
    __typename
    headline
    headlineHighlight
    headlineSecondary
    subheadline
    inputPlaceholder
    ctaButtonText
    secondaryButtonText
  }
  mirror {
    __typename
    title
    cards {
      __typename
      title
      text
    }
    closingStatement
  }
  howItWorks {
    __typename
    title
    steps {
      __typename
      iconName
      title
      text
    }
  }
  intelligence {
    __typename
    title
    subtitle
    pillars {
      __typename
      iconName
      title
      text
    }
  }
  trophy {
    __typename
    title
    subtitle
    videoTypes {
      __typename
      title
      subtitle
    }
    guarantee {
      __typename
      title
      text
    }
    galleryRow1 {
      __typename
      url
      type
      title
    }
    galleryRow2 {
      __typename
      url
      type
      title
    }
    galleryRow3 {
      __typename
      url
      type
      title
    }
  }
  offer {
    __typename
    title
    packageName
    packageSubtitle
    price
    priceNote
    features
    ctaButtonText
  }
  faq {
    __typename
    title
    items {
      __typename
      question
      answer
    }
  }
  footer {
    __typename
    copyright
    description
    links {
      __typename
      text
      href
    }
  }
}
